### ISSUE TITLE
Test all material_proprety options

### ISSUE THREAD

**Issue by masterleinad** [ORNL-CEES/mfmg#199]
Currently, the solver doesn't converge for `discontinuous`, but gives similar results for `constant`, `linear` and `linear_x`. We should make sure that all options actually work.

**Comment by Rombur** [comment]
Have you try both matrix-based and matrix-free? What parameters did you try?

**Comment by masterleinad** [comment]
The matrix-based code path in `hierarchy_driver` seems to work with
```
input file: hierarchy_input.info, dimension: 2, matrix-free: 0, fe_degree: 4, solver_tolerance: 1e-06
```
and
```
eigensolver
{
  "number of eigenvectors" 1
  tolerance 1e-14
}

smoother
{
  type  "Gauss-Seidel"
}

"is preconditioner" true

agglomeration
{
  partitioner block
  nx 2
  ny 2
  nz 2
}

material_property
{
  type discontinuous
}

laplace
{
  distort_random true
  reordering None
  n_refinements 5
}
```
while the `matrix-free` one doesn't.

**Comment by Rombur** [comment]
OK I wonder if it's because of the smoother. I think that matrix-free is using Jacobi (we say Chebyshev but by default we are really using Jacobi). That's not as good as Gauss-Seidel.

**Comment by masterleinad** [comment]
It's not just bad, but not converging at all:
```
Iterative method reported convergence failure in step 16641. The residual in the last step was 2230.38.
```

**Comment by masterleinad** [comment]
Even `PreconditionIdentity` doesn't work...
