### ISSUE TITLE
Add new Smoother

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/mfmg#99]
The current smoothers require an Epetra_CrsMatrix. This, of course, does not work in the matrix-free case where we need to use [Jacobi](https://dealii.org/developer/doxygen/deal.II/classPreconditionJacobi.html) (since we know the diagonal) or [Chebyshev](https://dealii.org/developer/doxygen/deal.II/classPreconditionChebyshev.html).

**Comment by Rombur** [comment]
Closed by #109

**Comment by dalg24** [comment]
Actually it was closed by #101 and for the record we went with Chebyshev
